name = "github-search"
main = "dist/github-search/server/worker-bundle.mjs"
no_bundle = true
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/github-search/browser"
binding = "ASSETS"
